site_name: Project Portfolio - Marc-Olivier Beaulieu
repo_name: github/RacoonDOEggs
#repo_url: https://github.com/RacoonDOEggs/RacoonDOEggs.github.io.git
site_url: https://github.com/RacoonDOEggs
copyright: Marc-Olivier Beaulieu

nav:
  - English:
    - Home: index.md
    - Projects:
      - Baja UdeS: nav/eng/baja_udes.md
  - Fran√ßais: 
    - Accueil: nav/fr/index_fr.md

theme:
  name: dracula
  logo: assets/img/Raccoon/RaccoonIcon.png
  favicon: assets/img/Raccoon/RaccoonIcon.png
